# Generated by Django 5.2.6 on 2025-09-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhis2entity',
            name='full_data',
        ),
    ]
