# Generated by Django 5.2.6 on 2025-09-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0002_remove_dhis2entity_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfiguration',
            name='execution_mode',
            field=models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Automatique'), ('scheduled', 'Planifié')], default='manual', help_text="Mode d'exécution de la synchronisation", max_length=15),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='import_strategy',
            field=models.CharField(choices=[('CREATE', 'Création seulement'), ('UPDATE', 'Mise à jour seulement'), ('CREATE_AND_UPDATE', 'Création et mise à jour'), ('DELETE', 'Suppression')], default='CREATE_AND_UPDATE', help_text="Stratégie d'import lors de la synchronisation", max_length=20),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='max_page_size',
            field=models.IntegerField(default=50, help_text='Taille maximale de page pour la récupération des données'),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='merge_mode',
            field=models.CharField(choices=[('REPLACE', 'Remplacement complet'), ('MERGE', 'Fusion/mise à jour')], default='MERGE', help_text="Mode de fusion lors de l'import (REPLACE ou MERGE)", max_length=10),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='supports_paging',
            field=models.BooleanField(default=True, help_text='Activer la pagination lors de la récupération'),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='sync_end_date',
            field=models.DateField(default=datetime.date.today, help_text="Date de fin pour la synchronisation des données (par défaut: aujourd'hui)"),
        ),
        migrations.AddField(
            model_name='syncconfiguration',
            name='sync_start_date',
            field=models.DateField(blank=True, help_text='Date de début pour la synchronisation des données (laissez vide pour toutes les données)', null=True),
        ),
        migrations.AlterField(
            model_name='syncconfiguration',
            name='schedule_enabled',
            field=models.BooleanField(default=False, help_text='Activer la planification automatique'),
        ),
        migrations.AlterField(
            model_name='syncconfiguration',
            name='schedule_interval',
            field=models.IntegerField(default=60, help_text='Intervalle en minutes pour la planification'),
        ),
    ]
