# Generated by Django 4.2.7 on 2025-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0003_syncconfiguration_execution_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis2instance',
            name='connection_status',
            field=models.BooleanField(blank=True, default=None, help_text='Statut de connexion (True=connecté, False=déconnecté, None=non testé)', null=True),
        ),
        migrations.AddField(
            model_name='dhis2instance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Instance active/inactive'),
        ),
        migrations.AddField(
            model_name='dhis2instance',
            name='last_connection_test',
            field=models.DateTimeField(blank=True, help_text='Dernière vérification de connexion', null=True),
        ),
    ]
