# Generated by Django 4.2.7 on 2025-10-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0004_dhis2instance_connection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFilterAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('event', 'Événement'), ('tracker', 'Entité suivie (Tracker)')], default='event', help_text='Type de filtre : event (programme) ou tracker (entité suivie)', max_length=10)),
                ('program_uid', models.CharField(help_text='UID du programme DHIS2 (pour les events) ou du trackedEntityType (pour tracker)', max_length=11)),
                ('program_name', models.CharField(blank=True, help_text="Nom du programme ou de l'entité suivie (optionnel, pour information)", max_length=255, null=True)),
                ('date_attribute_uid', models.CharField(help_text="UID de l'attribut/dataElement DHIS2 à utiliser pour filtrer par date", max_length=11)),
                ('date_attribute_name', models.CharField(blank=True, help_text="Nom de l'attribut/dataElement (optionnel, pour information)", max_length=255, null=True)),
                ('default_to_created', models.BooleanField(default=True, help_text="Utiliser 'created' comme valeur par défaut si l'attribut n'est pas disponible")),
                ('is_active', models.BooleanField(default=True, help_text='Configuration active/inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dhis2_instance', models.ForeignKey(help_text='Instance DHIS2 concernée', on_delete=django.db.models.deletion.CASCADE, related_name='date_filter_attributes', to='dhis_app.dhis2instance')),
            ],
            options={
                'verbose_name': 'Attribut de filtre de date',
                'verbose_name_plural': 'Attributs de filtre de date',
                'ordering': ['program_name', 'program_uid'],
                'indexes': [models.Index(fields=['dhis2_instance', 'filter_type'], name='dhis_app_da_dhis2_i_8877f6_idx'), models.Index(fields=['program_uid'], name='dhis_app_da_program_b1e4e8_idx'), models.Index(fields=['is_active'], name='dhis_app_da_is_acti_919d02_idx')],
                'unique_together': {('dhis2_instance', 'filter_type', 'program_uid')},
            },
        ),
    ]
