# Generated by Django 4.2.7 on 2025-10-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0005_datefilterattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefilterattribute',
            name='dhis2_instance',
            field=models.ForeignKey(help_text='Instance DHIS2 source concernée', limit_choices_to={'is_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='date_filter_attributes', to='dhis_app.dhis2instance'),
        ),
    ]
