# Generated by Django 4.2.7 on 2025-10-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis_app', '0006_alter_datefilterattribute_dhis2_instance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datefilterattribute',
            name='dhis_app_da_is_acti_919d02_idx',
        ),
        migrations.RemoveField(
            model_name='datefilterattribute',
            name='is_active',
        ),
    ]
